/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description 会員・職員共通ログイン。roleによって返却情報が異なる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example coach_001@example.jp
                         */
                        email: string;
                        /** @example coach001 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description JWT トークン */
                            token?: string;
                            user?: components["schemas"]["AuthUser"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ログアウト成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ログイン中ユーザーの情報取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 認証ユーザー情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthUser"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/member/learning-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の学習記録一覧取得 */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 学習記録一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningLog"][];
                    };
                };
            };
        };
        put?: never;
        /** 自分の学習記録を追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LearningLogInput"];
                };
            };
            responses: {
                /** @description 追加成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningLog"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/member/learning-logs/{logId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 自分の学習記録を更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    logId: components["parameters"]["logId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LearningLogInput"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningLog"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** 自分の学習記録を削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    logId: components["parameters"]["logId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/member/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 自分のダッシュボードデータ取得
         * @description ストリーク・デイリーゴール・カウントダウン・教材進捗をまとめて返す
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ダッシュボードデータ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberDashboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/member/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の達成率・学習時間の集計データ取得 */
        get: {
            parameters: {
                query: {
                    unit: "day" | "week" | "month";
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 集計データ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberAnalysis"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会員一覧取得 */
        get: {
            parameters: {
                query?: {
                    keyword?: string;
                    status?: "受講中" | "休会中" | "卒業済み";
                    minRate?: number;
                    maxRate?: number;
                    residence?: string;
                    travelCountry?: string;
                    progosLevel?: string;
                    textbookId?: string;
                    /** @description 最終ログインからの日数（以内） */
                    lastLoginDays?: number;
                    graduateDateFrom?: string;
                    graduateDateTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 会員一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            members?: components["schemas"]["MemberSummary"][];
                            total?: number;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 会員を1件登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemberInput"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 会員 CSV 一括インポート */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description インポート結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            imported?: number;
                            skipped?: number;
                            errors?: {
                                row?: number;
                                message?: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会員一覧を CSV エクスポート */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV ファイル */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会員カルテ詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 会員詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** 会員情報更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemberInput"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
            };
        };
        post?: never;
        /** 会員を削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/{memberId}/learning-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 特定会員の学習記録一覧取得（職員用） */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 学習記録一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningLog"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/{memberId}/coaching-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** コーチング記録一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description コーチング記録一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoachingRecord"][];
                    };
                };
            };
        };
        put?: never;
        /** コーチング記録追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CoachingRecordInput"];
                };
            };
            responses: {
                /** @description 追加成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoachingRecord"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/{memberId}/continuation-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 継続プラン一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 継続プラン一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContinuationPlan"][];
                    };
                };
            };
        };
        put?: never;
        /** 継続プラン追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContinuationPlanInput"];
                };
            };
            responses: {
                /** @description 追加成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContinuationPlan"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/members/{memberId}/progos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 特定会員の PROGOS スコア履歴取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PROGOS スコア一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgosScore"][];
                    };
                };
            };
        };
        put?: never;
        /** PROGOS スコア追加（職員用） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProgosScoreInput"];
                };
            };
            responses: {
                /** @description 追加成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgosScore"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/progos/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** PROGOS スコア CSV 一括インポート（職員用） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description インポート結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            imported?: number;
                            errors?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/textbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 教材一覧取得（name・category で部分一致検索） */
        get: {
            parameters: {
                query?: {
                    /** @description 教材名の部分一致 */
                    name?: string;
                    /** @description カテゴリの部分一致 */
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 教材一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            textbooks?: components["schemas"]["Textbook"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 教材追加（職員用） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TextbookInput"];
                };
            };
            responses: {
                /** @description 追加成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Textbook"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/textbooks/{textbookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 教材詳細取得（職員用） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    textbookId: components["parameters"]["textbookId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 教材詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Textbook"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 教材更新（職員用） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    textbookId: components["parameters"]["textbookId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TextbookInput"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Textbook"];
                    };
                };
            };
        };
        post?: never;
        /** 教材削除（職員用） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    textbookId: components["parameters"]["textbookId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** スタッフ一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description スタッフ一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Staff"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI 統計取得 */
        get: {
            parameters: {
                query?: {
                    period?: "1w" | "1m" | "3m" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KPI 統計 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/dashboard/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 要フォロー会員一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 要フォロー会員 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FollowUpList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example UNAUTHORIZED */
            code?: string;
            /** @example 認証が必要です */
            message?: string;
        };
        AuthUser: {
            id?: string;
            /** Format: email */
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "member" | "coach" | "consultant" | "cs";
        };
        /** @enum {string} */
        MemberStatus: "入学手続き中" | "受講中" | "休会中" | "卒業" | "継続中" | "再入学手続き中" | "途中退会";
        /** @description 会員一覧の行 */
        MemberSummary: {
            /**
             * Format: uuid
             * @description システムID（UUID）
             */
            id?: string;
            /**
             * @description 会員番号（業務コード）
             * @example 10001
             */
            code?: string;
            /**
             * @description 表示名（姓 名）
             * @example 見本 一郎
             */
            name?: string;
            nickname?: string;
            status?: components["schemas"]["MemberStatus"];
            /** @example 6ヶ月プラン */
            plan?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            graduateDate?: string;
            /** @example Lower-Intermediate */
            currentClass?: string;
            /**
             * @description 今月の達成率（%）
             * @example 65
             */
            achievementRate?: number;
            /**
             * @description 今月の学習時間（時間）
             * @example 38
             */
            monthlyHours?: number;
            /**
             * @description 連続学習日数
             * @example 7
             */
            streak?: number;
            /** Format: date-time */
            lastLoginAt?: string;
        };
        /** @description 会員詳細（カルテ）。フィールドは既存クライアントの member オブジェクトに準拠。 */
        Member: components["schemas"]["MemberSummary"] & {
            /** @description 姓のイニシャル */
            initial?: string;
            lastNameKanji?: string;
            firstNameKanji?: string;
            lastNameKana?: string;
            firstNameKana?: string;
            lastNameAlpha?: string;
            firstNameAlpha?: string;
            /** Format: email */
            email?: string;
            /** @example 男性 */
            gender?: string;
            /** Format: date */
            birthDate?: string;
            phone?: string;
            /** @example 会社員 */
            occupation?: string;
            occupationNote?: string;
            /** @example 日本 */
            residence?: string;
            residenceOverseas?: string;
            /**
             * Format: date
             * @description オリエンテーション実施日
             */
            enrollmentDate?: string;
            /** @description オリエン担当スタッフの UUID（未割り当ては省略） */
            orientStaffId?: string;
            initialClass?: string;
            nativecamp?: string;
            /** @example 90 */
            dailyTargetMinutes?: number;
            /** @example オーストラリア */
            travelCountry?: string;
            /** @example シドニー */
            travelCity?: string;
            /** Format: date */
            travelDate?: string;
            /** @example 語学学校 */
            travelReason?: string;
            travelNote?: string;
            englishScores?: {
                toeicLR?: number;
                toeicSW?: number;
                toefl?: number;
                ielts?: string;
                eiken?: string;
                other?: string;
            };
            coachLearningGoal?: string;
            note?: string;
            /** @description 担当コンサルタントのスタッフ UUID（未割り当ては省略） */
            consultantStaffId?: string;
            /** @description 担当CSのスタッフ UUID（未割り当ては省略） */
            csStaffId?: string;
            /** @description 継続プラン履歴（カルテ「4. 継続プラン履歴」） */
            continuationPlans?: components["schemas"]["ContinuationPlanHistoryItem"][];
            suspension?: components["schemas"]["Suspension"];
        };
        /** @description 継続プラン履歴の1行（カルテ表示用。planType/months/期間/備考） */
        ContinuationPlanHistoryItem: {
            /** Format: uuid */
            id?: string;
            /** @example 給付金6ヶ月プラン */
            planType?: string;
            /** @example 6 */
            months?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            note?: string;
        };
        /** @description 休会情報（休会していなければ null） */
        Suspension: {
            /** Format: date */
            suspendedFrom?: string;
            /** Format: date */
            suspendedUntil?: string;
            /**
             * Format: date
             * @description 休会日数ぶん延長後の卒業予定日
             */
            graduateDate?: string;
            /**
             * Format: date
             * @description 休会前の卒業予定日
             */
            preSuspendGraduateDate?: string;
        } | null;
        /** @description 会員登録・更新の入力。既存クライアントのフォーム（nm-* / em-*）の flat なフィールドに準拠。登録時はフォームが自動生成した仮パスワードを含む（member_credentials へ保存）。 */
        MemberInput: {
            /** @description 【会員ID】（必須）5桁数値の業務コード */
            code: string;
            /** @description 【姓（漢字）】（必須） */
            lastNameKanji: string;
            /** @description 【名（漢字）】（必須） */
            firstNameKanji: string;
            /** @description 【姓（カタカナ）】（必須） */
            lastNameKana?: string;
            /** @description 【名（カタカナ）】（必須） */
            firstNameKana?: string;
            /** @description 【姓（アルファベット）】（必須） */
            lastNameAlpha?: string;
            /** @description 【名（アルファベット）】（必須） */
            firstNameAlpha?: string;
            /** @description 【ニックネーム】（任意） */
            nickname?: string;
            /**
             * Format: email
             * @description 【メールアドレス】（必須）ログインIDになる
             */
            email: string;
            /** @description 【性別】（必須）男性 / 女性 / その他 */
            gender?: string;
            /**
             * Format: date
             * @description 【生年月日】（必須）
             */
            birthDate?: string;
            /** @description 【電話番号】（必須） */
            phone?: string;
            /** @description 【職業】（任意）会社員 / 経営者・役員 / 自営業・フリーランス / 公務員 / 大学・大学院生 / 中学・高校生 / パート・アルバイト / 無職 / その他 */
            occupation?: string;
            /** @description 【職業 備考】（任意）「その他」選択時の詳細など */
            occupationNote?: string;
            /** @description 【入学時の在住国】（任意）日本 / 海外 */
            residence?: string;
            /** @description 【海外の国名】在住国で「海外」選択時は必須 */
            residenceOverseas?: string;
            /** @description 【入会プラン】（必須）6ヶ月プラン / 給付金6ヶ月プラン / 給付金9ヶ月プラン / 給付金12ヶ月プラン */
            plan?: string;
            /** @description 【ステータス】（必須）入学手続き中 / 再入学手続き中 / 受講中 / 継続中 / 休会中 / 卒業 / 途中退会。日付から算出できないもの（途中退会 等）のみ反映 */
            status?: components["schemas"]["MemberStatus"];
            /**
             * Format: date
             * @description 【オリエン実施日】（任意）
             */
            enrollmentDate?: string;
            /** @description 【オリエン担当者】（任意）role=Coach のスタッフ UUID。「その他」選択時は "OTHER"（担当行は作らない） */
            orientStaffId?: string;
            /**
             * Format: date
             * @description 【受講開始日】（任意）初回コーチング日
             */
            startDate?: string;
            /**
             * Format: date
             * @description 【卒業予定日】（任意）プランから自動算出 / 手動上書き可
             */
            graduateDate?: string;
            /** @description 【入学時クラス】（必須）Beginner / Lower-Intermediate / Intermediate & Above / Higher Education Prep */
            initialClass?: string;
            /** @description 【現在のクラス】（必須）Beginner / Lower-Intermediate / Intermediate & Above / Higher Education Prep */
            currentClass?: string;
            /** @description 【ネイティブキャンプ】（必須）未選択 / 未導入 / 導入済み */
            nativecamp?: string;
            /** @description 【1日の目標学習時間(分)】（必須）1〜1440。達成率の分母 */
            dailyTargetMinutes?: number;
            /** @description 【担当コンサルタント】（必須）role=Consultant のスタッフ UUID。「その他」選択時は "OTHER"（担当行は作らない） */
            consultantStaffId?: string;
            /** @description 【担当CS】（必須）role=CS のスタッフ UUID。「その他」選択時は "OTHER"（担当行は作らない） */
            csStaffId?: string;
            /** @description 【渡航先（国）】（任意）オーストラリア / カナダ / イギリス / ニュージーランド / フィリピン / その他 / 未決定 */
            travelCountry?: string;
            /** @description 【渡航先（都市）】（任意）渡航先（国）に連動 */
            travelCity?: string;
            /**
             * Format: date
             * @description 【渡航時期】（任意）未来日のみ
             */
            travelDate?: string;
            /** @description 【渡航理由】（任意）語学学校 / ワーキングホリデー / 進学（大学・大学院）/ 高校留学 / 海外就職 / その他 */
            travelReason?: string;
            /** @description 【在住・渡航 備考】（任意） */
            travelNote?: string;
            /** @description 【TOEIC L&R】（任意）10〜990 */
            scoreToeicLR?: number;
            /** @description 【TOEIC S&W】（任意）0〜400 */
            scoreToeicSW?: number;
            /** @description 【TOEFL iBT】（任意）0〜120 */
            scoreToefl?: number;
            /** @description 【IELTS】（任意） */
            scoreIelts?: string;
            /** @description 【英検】（任意）5級〜1級 */
            scoreEiken?: string;
            /** @description 【その他 検定名・スコア】（任意・自由入力）例：ケンブリッジ英検 FCE B2 */
            scoreOther?: string;
            /** @description 【学習目標・目的】（任意） */
            coachLearningGoal?: string;
            /** @description 【備考】（任意）特記事項、家族情報など */
            note?: string;
        };
        LearningLog: {
            /** @example LOG_10001_20260617_001 */
            id?: string;
            memberId?: string;
            /** Format: date */
            date?: string;
            textbookId?: string;
            /**
             * @description 学習時間（分）
             * @example 75
             */
            durationMinutes?: number;
            comment?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LearningLogInput: {
            /** Format: date */
            date: string;
            textbookId: string;
            /** @example 75 */
            durationMinutes: number;
            comment?: string;
        };
        CoachingRecord: {
            id?: string;
            memberId?: string;
            /** Format: date */
            date?: string;
            coachId?: string;
            coachName?: string;
            /** @enum {string} */
            type?: "教材選定" | "オリエンテーション" | "初回コーチング" | "通常コーチング";
            selectedTextbooks?: components["schemas"]["TextbookAssignment"][];
            sharedNote?: string;
            internalNote?: string;
            /** @enum {string} */
            continuationDecision?: "継続" | "卒業";
            /** Format: date-time */
            createdAt?: string;
        };
        CoachingRecordInput: {
            /** Format: date */
            date: string;
            /** @enum {string} */
            type: "教材選定" | "オリエンテーション" | "初回コーチング" | "通常コーチング";
            selectedTextbooks?: components["schemas"]["TextbookAssignment"][];
            sharedNote?: string;
            internalNote?: string;
            /** @enum {string} */
            continuationDecision?: "継続" | "卒業";
        };
        TextbookAssignment: {
            textbookId: string;
            note?: string;
            dailyGoalMinutes?: number;
        };
        ContinuationPlan: {
            id?: string;
            memberId?: string;
            /** @enum {string} */
            type?: "継続" | "休会" | "再入会";
            plan?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            note?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ContinuationPlanInput: {
            /** @enum {string} */
            type: "継続" | "休会" | "再入会";
            plan?: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string;
            note?: string;
        };
        ProgosScore: {
            id?: string;
            memberId?: string;
            /** Format: date */
            date?: string;
            /** @example A2 */
            level?: string;
            reading?: number;
            writing?: number;
            listening?: number;
            speaking?: number;
        };
        ProgosScoreInput: {
            /** Format: date */
            date: string;
            level: string;
            reading?: number;
            writing?: number;
            listening?: number;
            speaking?: number;
        };
        /** @description 教材マスタ。id はシステムUUID、textbookCode が業務コード（T01等）。 */
        Textbook: {
            /**
             * Format: uuid
             * @description システムID（UUID）
             */
            id?: string;
            /**
             * @description 教材コード（業務キー・UNIQUE）
             * @example T01
             */
            textbookCode?: string;
            /** @example キクタン【Entry】 */
            name?: string;
            /**
             * @description タイプ（自由入力）
             * @example 単語/フレーズ
             */
            category?: string;
            /** @enum {string} */
            unit?: "Day" | "Chapter" | "Lesson" | "回";
            /** @example #2E86C1 */
            color?: string;
            /** Format: uri */
            iconUrl?: string;
            /** Format: uri */
            manualUrl?: string;
            note?: string;
        };
        TextbookInput: {
            /** @description 教材コード（業務キー・ユーザー入力・UNIQUE） */
            textbookCode: string;
            name: string;
            category: string;
            /** @enum {string} */
            unit: "Day" | "Chapter" | "Lesson" | "回";
            color?: string;
            /** Format: uri */
            iconUrl?: string;
            /** Format: uri */
            manualUrl?: string;
            note?: string;
        };
        Staff: {
            /** @example MW001 */
            id?: string;
            name?: string;
            /** @enum {string} */
            role?: "Coach" | "Consultant" | "CS";
            /** Format: email */
            email?: string;
        };
        MemberDashboard: {
            /** @description 連続学習日数 */
            streak?: number;
            dailyGoal?: {
                targetMinutes?: number;
                achievedMinutes?: number;
                rate?: number;
            };
            countdowns?: {
                daysToGraduate?: number;
                daysToTravel?: number;
            };
            textbookProgress?: {
                textbookId?: string;
                name?: string;
                completedUnits?: number;
                totalUnits?: number;
            }[];
            graduatedTextbooks?: {
                textbookId?: string;
                name?: string;
                /** Format: date */
                completedAt?: string;
            }[];
            /** @description 前回コーチングから30日以上経過しているか */
            coachingReminderNeeded?: boolean;
        };
        MemberAnalysis: {
            /** @enum {string} */
            unit?: "day" | "week" | "month";
            data?: {
                /** @description 日付・週・月のラベル */
                label?: string;
                achievementRate?: number;
                learningMinutes?: number;
            }[];
        };
        DashboardStats: {
            /** @enum {string} */
            period?: "1w" | "1m" | "3m" | "all";
            averageAchievementRate?: number;
            totalLearningHours?: number;
            activeMemberCount?: number;
            monthlyTrend?: {
                /** @example 2026-06 */
                month?: string;
                averageAchievementRate?: number;
                totalLearningHours?: number;
            }[];
        };
        FollowUpList: {
            notLoggedIn3Months?: components["schemas"]["MemberSummary"][];
            /** @description 達成率 0〜30% の会員 */
            lowAchievement?: components["schemas"]["MemberSummary"][];
            /** @description 学習記録がない会員 */
            noLearningLog?: components["schemas"]["MemberSummary"][];
            /** @description コーチング受診待ちの会員 */
            pendingCoaching?: components["schemas"]["MemberSummary"][];
            /** @description 卒業判定候補の会員 */
            graduationCandidate?: components["schemas"]["MemberSummary"][];
        };
    };
    responses: {
        /** @description 認証エラー（トークン未提供または無効） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 権限エラー（ロールが不足） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description リソースが見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        memberId: string;
        logId: string;
        textbookId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
