/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as TextbooksRouteImport } from './app/routes/textbooks'
import { Route as StaffRouteImport } from './app/routes/staff'
import { Route as ProgosRouteImport } from './app/routes/progos'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as KarteRouteImport } from './app/routes/karte'
import { Route as DashboardRouteImport } from './app/routes/dashboard'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as MembersIndexRouteImport } from './app/routes/members/index'

const TextbooksRoute = TextbooksRouteImport.update({
  id: '/textbooks',
  path: '/textbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgosRoute = ProgosRouteImport.update({
  id: '/progos',
  path: '/progos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KarteRoute = KarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/karte': typeof KarteRoute
  '/login': typeof LoginRoute
  '/progos': typeof ProgosRoute
  '/staff': typeof StaffRoute
  '/textbooks': typeof TextbooksRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/karte': typeof KarteRoute
  '/login': typeof LoginRoute
  '/progos': typeof ProgosRoute
  '/staff': typeof StaffRoute
  '/textbooks': typeof TextbooksRoute
  '/members': typeof MembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/karte': typeof KarteRoute
  '/login': typeof LoginRoute
  '/progos': typeof ProgosRoute
  '/staff': typeof StaffRoute
  '/textbooks': typeof TextbooksRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/karte'
    | '/login'
    | '/progos'
    | '/staff'
    | '/textbooks'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/karte'
    | '/login'
    | '/progos'
    | '/staff'
    | '/textbooks'
    | '/members'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/karte'
    | '/login'
    | '/progos'
    | '/staff'
    | '/textbooks'
    | '/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KarteRoute: typeof KarteRoute
  LoginRoute: typeof LoginRoute
  ProgosRoute: typeof ProgosRoute
  StaffRoute: typeof StaffRoute
  TextbooksRoute: typeof TextbooksRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/textbooks': {
      id: '/textbooks'
      path: '/textbooks'
      fullPath: '/textbooks'
      preLoaderRoute: typeof TextbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progos': {
      id: '/progos'
      path: '/progos'
      fullPath: '/progos'
      preLoaderRoute: typeof ProgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karte': {
      id: '/karte'
      path: '/karte'
      fullPath: '/karte'
      preLoaderRoute: typeof KarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KarteRoute: KarteRoute,
  LoginRoute: LoginRoute,
  ProgosRoute: ProgosRoute,
  StaffRoute: StaffRoute,
  TextbooksRoute: TextbooksRoute,
  MembersIndexRoute: MembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
